export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const CHANGE_KEYBOARD = "CHANGE_KEYBOARD";
export const CHANGE_TEMP_KEYBOARD = "CHANGE_TEMP_KEYBOARD";
export const CHANGE_SINGLE_KEY = "CHANGE_SINGLE_KEY";
export const CHANGE_CURRENT_KEYBOARD = "CHANGE_CURRENT_KEYBOARD";
